'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class client
    Public Property ClientID As Integer
    Public Property CompanyName As String
    Public Property Location As String
    Public Property Email As String
    Public Property EnrollmentDate As Date
    Public Property LastAccessDate As Date

End Class
